name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --label nodeType=$CI_PROJECT_NAME-$GITLAB_USER_ID -t $CI_REGISTRY_IMAGE:latest -f Dockerfile
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        docker push $CI_REGISTRY_IMAGE:latest
        docker logout $CI_REGISTRY
