name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build  . --label nodeType=$CI_PROJECT_NAME-$GITLAB_USER_ID  --file Dockerfile --tag jelastic-symfony:$(date +%s)
